import { Link } from "react-router-dom";
import { ArrowLeft, ScrollText } from "lucide-react";
import Seo from "../components/Seo";
import { Button } from "../components/ui/button";

const LAST_UPDATED = "27 April 2026";
const CONTACT_EMAIL = "hello@achint.dev";
const SITE_URL = "https://tingutales.com";

interface PolicySection {
  id: string;
  title: string;
  content: React.ReactNode;
}

const sections: PolicySection[] = [
  {
    id: "terms",
    title: "Terms of Service",
    content: (
      <div className="space-y-4 text-[#1E1B4B]/75 leading-relaxed">
        <p>
          By accessing or using Tingu Tales (<strong>"{SITE_URL}"</strong>), you agree to be bound by these Terms of Service. If you do not agree, please do not use our service.
        </p>
        <h3 className="font-semibold text-[#1E1B4B] text-base">1. Eligibility</h3>
        <p>
          Tingu Tales is intended for use by adults (18 years or older) on behalf of children. You must have parental or guardian authority to create an account and generate storybooks for a child. By using our service you confirm that you are at least 18 years old.
        </p>
        <h3 className="font-semibold text-[#1E1B4B] text-base">2. Account Responsibilities</h3>
        <p>
          You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. Notify us immediately at <a href={`mailto:${CONTACT_EMAIL}`} className="text-[#3730A3] hover:underline">{CONTACT_EMAIL}</a> if you suspect unauthorised access.
        </p>
        <h3 className="font-semibold text-[#1E1B4B] text-base">3. Permitted Use</h3>
        <p>
          You may use Tingu Tales solely for personal, non-commercial purposes — to create storybooks for children in your care. You may not resell, redistribute, or commercialise any content generated by the service without our prior written consent.
        </p>
        <h3 className="font-semibold text-[#1E1B4B] text-base">4. Intellectual Property</h3>
        <p>
          The Tingu Tales platform, brand, and underlying technology are owned by Tingu Tales. Storybook PDFs you generate are licensed to you for personal use. You retain no rights to the AI models, prompt engineering, or generation infrastructure.
        </p>
        <h3 className="font-semibold text-[#1E1B4B] text-base">5. Prohibited Conduct</h3>
        <ul className="list-disc pl-5 space-y-1">
          <li>Uploading images of individuals other than the child for whom the storybook is being created.</li>
          <li>Generating content that is harmful, hateful, sexually explicit, or otherwise inappropriate for children.</li>
          <li>Attempting to reverse-engineer, scrape, or abuse the platform.</li>
          <li>Using the service to violate any applicable law or regulation.</li>
        </ul>
        <h3 className="font-semibold text-[#1E1B4B] text-base">6. Disclaimers</h3>
        <p>
          Tingu Tales is provided "as is." We do not guarantee that the service will be uninterrupted, error-free, or that generated content will be free from inaccuracies. AI-generated stories are reviewed for quality but may occasionally produce unexpected results.
        </p>
        <h3 className="font-semibold text-[#1E1B4B] text-base">7. Limitation of Liability</h3>
        <p>
          To the maximum extent permitted by law, Tingu Tales shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service.
        </p>
        <h3 className="font-semibold text-[#1E1B4B] text-base">8. Changes to Terms</h3>
        <p>
          We may update these Terms at any time. Continued use of the service after changes constitutes your acceptance of the revised Terms. We will notify users of material changes by email or in-app notice.
        </p>
      </div>
    ),
  },
  {
    id: "privacy",
    title: "Privacy Policy",
    content: (
      <div className="space-y-4 text-[#1E1B4B]/75 leading-relaxed">
        <p>
          Your privacy — and your child's privacy — is important to us. This policy explains what data we collect, how we use it, and your rights.
        </p>
        <h3 className="font-semibold text-[#1E1B4B] text-base">1. Data We Collect</h3>
        <ul className="list-disc pl-5 space-y-1">
          <li><strong>Account data:</strong> name and email address when you sign in with Google.</li>
          <li><strong>Child profile data:</strong> the child's first name, age group, gender, and language preference — provided by you to personalise stories.</li>
          <li><strong>Child photo / avatar:</strong> a photo you upload to create the child's illustrated avatar. This image is used solely for generating the avatar and is automatically deleted within <strong>30 days</strong> of upload. We encourage you to delete it yourself from the app as soon as the avatar has been generated.</li>
          <li><strong>Story content:</strong> story text and generated illustrations, stored to let you download your storybook PDF.</li>
          <li><strong>Payment data:</strong> payment is processed by Razorpay. We do not store card details. We retain order identifiers and amounts for billing records.</li>
          <li><strong>Usage data:</strong> anonymous analytics (page views, feature interactions) to improve the product.</li>
        </ul>
        <h3 className="font-semibold text-[#1E1B4B] text-base">2. Children's Data</h3>
        <p>
          Tingu Tales does not knowingly collect personal data directly from children. All child profile information is provided by a parent or guardian. We do not sell, share, or use children's data for advertising purposes. The child's photo is used exclusively to generate the illustrated avatar and is never shared with third parties. Once the avatar is generated, we ask you to delete the photo from the app immediately. If not deleted by you, the original photo is <strong>automatically deleted within 30 days</strong> of upload. The generated avatar illustration (not the original photo) is retained to maintain consistency across story pages.
        </p>
        <h3 className="font-semibold text-[#1E1B4B] text-base">3. How We Use Your Data</h3>
        <ul className="list-disc pl-5 space-y-1">
          <li>To generate personalised storybooks.</li>
          <li>To send you your completed storybook and transactional emails.</li>
          <li>To process payments and manage refunds.</li>
          <li>To improve our AI models and product experience using anonymised data.</li>
        </ul>
        <h3 className="font-semibold text-[#1E1B4B] text-base">4. Data Sharing</h3>
        <p>
          We do not sell your data. We share data only with trusted service providers who process it on our behalf (Google Cloud, Firebase, Razorpay, Google Gemini / Imagen AI APIs). Each provider is contractually obligated to protect your data.
        </p>
        <h3 className="font-semibold text-[#1E1B4B] text-base">5. Data Retention</h3>
        <p>
          We retain your account and story data as long as your account is active. Generated storybook images and PDFs are retained to allow re-downloads.
        </p>
        <p>
          <strong>Child photo:</strong> the original photo you upload is automatically deleted within <strong>30 days</strong> of upload. We encourage you to delete it yourself as soon as the avatar has been generated — you can do this from the child profile screen in the app. The generated avatar illustration is kept separately and is not the original photo.
        </p>
        <p>
          You can request full data deletion at any time (see Data Deletion below).
        </p>
        <h3 className="font-semibold text-[#1E1B4B] text-base">6. Security</h3>
        <p>
          Data is stored on Google Firebase with industry-standard encryption at rest and in transit. Access is restricted to authorised personnel and automated systems only.
        </p>
        <h3 className="font-semibold text-[#1E1B4B] text-base">7. Your Rights</h3>
        <p>
          You have the right to access, correct, or delete any personal data we hold about you or your child. Email us at <a href={`mailto:${CONTACT_EMAIL}`} className="text-[#3730A3] hover:underline">{CONTACT_EMAIL}</a> and we will respond within 7 business days.
        </p>
      </div>
    ),
  },
  {
    id: "refunds",
    title: "Refund Policy",
    content: (
      <div className="space-y-4 text-[#1E1B4B]/75 leading-relaxed">
        <h3 className="font-semibold text-[#1E1B4B] text-base">When you are eligible for a refund</h3>
        <p>
          We want you to be completely happy with your storybook. If we are unable to generate a completed storybook PDF due to a technical failure on our end, you are entitled to a full refund.
        </p>
        <h3 className="font-semibold text-[#1E1B4B] text-base">How to request a refund</h3>
        <p>
          Use the "Request Refund" option within the app on the relevant story, or email us at <a href={`mailto:${CONTACT_EMAIL}`} className="text-[#3730A3] hover:underline">{CONTACT_EMAIL}</a> within <strong>7 days</strong> of your purchase. Include your order reference and a brief description of the issue.
        </p>
        <h3 className="font-semibold text-[#1E1B4B] text-base">Processing time</h3>
        <p>
          Approved refunds are processed within 5–7 business days back to your original payment method via Razorpay.
        </p>
        <h3 className="font-semibold text-[#1E1B4B] text-base">Non-refundable situations</h3>
        <ul className="list-disc pl-5 space-y-1">
          <li>A completed storybook PDF has already been generated and downloaded successfully.</li>
          <li>The request is made more than 7 days after purchase.</li>
          <li>The issue was caused by incorrect information (e.g., wrong child name or language) provided during story creation.</li>
        </ul>
      </div>
    ),
  },
  {
    id: "content",
    title: "Content Policy",
    content: (
      <div className="space-y-4 text-[#1E1B4B]/75 leading-relaxed">
        <p>
          All content generated by Tingu Tales is designed to be safe, age-appropriate, and culturally respectful for children. Our AI systems are configured to:
        </p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Produce positive, educational, and emotionally enriching stories.</li>
          <li>Celebrate Indian culture, traditions, and languages without stereotyping.</li>
          <li>Never generate violent, sexually explicit, hateful, or harmful content.</li>
          <li>Avoid inclusion of brand names, political figures, or controversial real-world topics.</li>
        </ul>
        <p>
          Every generated story goes through an automated quality review. If you believe a generated story contains inappropriate content, please report it immediately at <a href={`mailto:${CONTACT_EMAIL}`} className="text-[#3730A3] hover:underline">{CONTACT_EMAIL}</a> and we will investigate and take corrective action.
        </p>
        <p>
          Users must not attempt to manipulate the story creation inputs to bypass these safeguards. Accounts found doing so may be suspended without refund.
        </p>
      </div>
    ),
  },
  {
    id: "data-deletion",
    title: "Data Deletion",
    content: (
      <div className="space-y-4 text-[#1E1B4B]/75 leading-relaxed">
        <p>
          You have the right to request deletion of all personal data we hold about you and your child at any time.
        </p>
        <h3 className="font-semibold text-[#1E1B4B] text-base">What gets deleted</h3>
        <ul className="list-disc pl-5 space-y-1">
          <li>Your account and authentication record.</li>
          <li>All child profiles associated with your account.</li>
          <li>The child's uploaded photo and generated avatar image.</li>
          <li>All story content, generated pages, and PDF files.</li>
          <li>Payment records (subject to legal retention requirements).</li>
        </ul>
        <h3 className="font-semibold text-[#1E1B4B] text-base">How to request deletion</h3>
        <p>
          Email <a href={`mailto:${CONTACT_EMAIL}`} className="text-[#3730A3] hover:underline">{CONTACT_EMAIL}</a> with the subject line <strong>"Data Deletion Request"</strong> from the email address associated with your account. We will confirm deletion within 7 business days.
        </p>
        <p>
          Note: Deleting your data is irreversible. Any storybook PDFs not downloaded before deletion cannot be recovered.
        </p>
      </div>
    ),
  },
  {
    id: "cookies",
    title: "Cookie Policy",
    content: (
      <div className="space-y-4 text-[#1E1B4B]/75 leading-relaxed">
        <p>
          Tingu Tales uses a minimal number of cookies and similar technologies to operate the service.
        </p>
        <h3 className="font-semibold text-[#1E1B4B] text-base">Essential cookies</h3>
        <p>
          We use Firebase Authentication session tokens to keep you logged in. These are strictly necessary for the service to function and cannot be disabled.
        </p>
        <h3 className="font-semibold text-[#1E1B4B] text-base">Analytics</h3>
        <p>
          We use anonymous, privacy-respecting analytics to understand how users interact with the platform (e.g., which features are most used). This data is aggregated and never linked to an individual user.
        </p>
        <h3 className="font-semibold text-[#1E1B4B] text-base">No advertising cookies</h3>
        <p>
          We do not use advertising networks or third-party tracking cookies. We do not display ads on Tingu Tales.
        </p>
      </div>
    ),
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#FDFBF7]">
      <Seo
        title="Terms & Policies - Tingu Tales"
        description="Read the Terms of Service, Privacy Policy, Refund Policy, Content Policy, Data Deletion, and Cookie Policy for Tingu Tales personalised children's storybooks."
        canonicalUrl="https://tingutales.com/terms"
      />

      <nav className="sticky top-0 z-50 border-b border-[#F3E8FF] bg-[#FDFBF7]/85 backdrop-blur-xl">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6">
          <Link to="/" className="flex items-center gap-3">
            <img src="/favicon.png" alt="Tingu Tales" className="h-10 w-10" />
            <span
              className="hidden text-2xl font-semibold tracking-tight text-[#1E1B4B] sm:inline"
              style={{ fontFamily: "Fredoka" }}
            >
              Tingu <span className="text-[#FF9F1C]">Tales</span>
            </span>
          </Link>
          <Button asChild variant="outline" className="rounded-full border-[#1E1B4B]/15 px-5 font-semibold text-[#1E1B4B] hover:bg-[#1E1B4B]/5">
            <Link to="/">
              <ArrowLeft className="h-4 w-4" strokeWidth={2.5} />
              Home
            </Link>
          </Button>
        </div>
      </nav>

      <main className="mx-auto max-w-4xl px-6 py-16">
        {/* Header */}
        <div className="mb-12 text-center">
          <div className="mb-5 inline-flex items-center gap-2 rounded-full bg-[#3730A3]/10 px-4 py-2 text-sm font-bold text-[#1E1B4B]">
            <ScrollText className="h-4 w-4 text-[#3730A3]" strokeWidth={2.5} />
            Legal &amp; Policies
          </div>
          <h1
            className="text-4xl font-semibold tracking-tight text-[#1E1B4B] sm:text-5xl"
            style={{ fontFamily: "Fredoka" }}
          >
            Terms &amp; Policies
          </h1>
          <p className="mx-auto mt-4 max-w-2xl text-base leading-relaxed text-[#1E1B4B]/65">
            Last updated: {LAST_UPDATED}. These policies govern your use of Tingu Tales. Please read them carefully.
          </p>
        </div>

        {/* Jump links */}
        <nav className="mb-12 rounded-2xl border-2 border-[#F3E8FF] bg-white p-6">
          <p className="mb-3 text-xs font-bold uppercase tracking-wider text-[#1E1B4B]/40">On this page</p>
          <ul className="space-y-1.5">
            {sections.map((s) => (
              <li key={s.id}>
                <a
                  href={`#${s.id}`}
                  className="text-sm font-medium text-[#3730A3] hover:text-[#1E1B4B] transition-colors"
                >
                  {s.title}
                </a>
              </li>
            ))}
          </ul>
        </nav>

        {/* Sections */}
        <div className="space-y-12">
          {sections.map((s) => (
            <section key={s.id} id={s.id} className="scroll-mt-24">
              <div className="mb-5 border-b-2 border-[#F3E8FF] pb-3">
                <h2
                  className="text-2xl font-semibold text-[#1E1B4B]"
                  style={{ fontFamily: "Fredoka" }}
                >
                  {s.title}
                </h2>
              </div>
              {s.content}
            </section>
          ))}
        </div>

        {/* Contact */}
        <div className="mt-16 rounded-2xl border-2 border-[#F3E8FF] bg-white p-8 text-center">
          <p className="text-base font-semibold text-[#1E1B4B] mb-2">Questions about these policies?</p>
          <p className="text-sm text-[#1E1B4B]/60 mb-4">
            We're happy to help. Reach out and we'll respond within 2 business days.
          </p>
          <a
            href={`mailto:${CONTACT_EMAIL}`}
            className="inline-flex items-center gap-2 rounded-full bg-[#3730A3] px-6 py-2.5 text-sm font-semibold text-white hover:bg-[#2e278f] transition-colors"
          >
            {CONTACT_EMAIL}
          </a>
        </div>
      </main>

      <footer className="border-t border-[#F3E8FF] py-8 mt-8">
        <div className="max-w-4xl mx-auto px-6 flex items-center justify-between text-sm text-[#1E1B4B]/50">
          <Link to="/" className="flex items-center gap-2 hover:text-[#1E1B4B] transition-colors">
            <img src="/favicon.png" alt="" className="w-6 h-6" />
            <span style={{ fontFamily: "Fredoka" }}>Tingu <span className="text-[#FF9F1C]">Tales</span></span>
          </Link>
          <p className="text-xs">© {new Date().getFullYear()} Tingu Tales. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
